name: CI on Push
 
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
jobs:
  build:  
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x      
    - name: Build
      shell: pwsh
      run: ./build.ps1 $(git rev-parse --short HEAD)
    - name: Push to MyGet
      env:
        PKG_URL: https://www.myget.org/F/bad-echo/api/v3/index.json
        PKG_API_KEY: ${{ secrets.MYGET_API_KEY }}
      run: ./push.ps1
      shell: pwsh
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts/**/*
